TEST_BENCH = register_tb
SUB_MODULE_FILES = ../../moudles/register.v

MODULE_FILES=${TEST_BENCH}.v ${SUB_MODULE_FILES}

ICESTORM_TOOLCHAIN = /usr/local
SIM_TOOLCHAIN = ${HOME}/.apio/packages/toolchain-iverilog

